# Generated by Django 3.1.5 on 2021-01-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userr_last_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userr',
            old_name='empid',
            new_name='username',
        ),
    ]
